#!/bin/bash
# Data PreProcessing for Genomics Project
# Fiona and Rayaan

# prerequisites for running this script: 
#
#
#
#

echo "*******Begin data preprocessing for Genomics project"
echo "*******FastQ --> BAM"


echo "*******format BAM (mark duplicates, sort by position)"
#Picard processing
#ordering bam
java -jar picard.jar SortSam I=exampleBAM.bam O=sorted.bam SO=coordinate
#mark duplicates
java -jar picard.jar MarkDuplicates I=sorted.bam O=nodups.bam M=metrics.txt
#add RG
java -jar picard.jar AddOrReplaceReadGroups I=nodups.bam O=final.bam RGID=id RGLB=solexa-123 RGPL=illumina RGPU=AXL2342 RGSM=NA12878 RGCN=bi RGDT=2016-04-10
#index bam
java -jar picard.jar BuildBamIndex I=final.bam


echo "*******indel realignment"
#create target intervals list 
java -jar GenomeAnalysisTK.jar -T RealignerTargetCreator -R human_reference.fasta -L 10:96000000-97000000 -known known_indels.vcf -I final.bam -o realignertargetcreator.intervals
#make file readable on IGV
awk -F '[:-]' 'BEGIN {OFS="\t"} {if($3=="") {print $1, $2-1, $2} else {print $1, $2-1, $3}}' realignertargetcreator.intervals > realignertargetcreator.bed 
#realign reads
java -Xmx8G -Djava.io.tmpdir=/tmp -jar GenomeAnalysisTK.jar -T IndelRealigner -R human_reference.fasta -targetIntervals realignertargetcreator.intervals -known known_indels.vcf -I final.bam -o indelrealigner.bam 

 
echo "*******BQSR -- base quality score recalibration" 
#analyze patterns of covariation in the sequence dataset 
java -jar GenomeAnalysisTK.jar -T BaseRecalibrator -R human_reference.fasta -I indelrealigner.bam -L 20 -knownSites dbsnp.vcf -knownSites gold_indels.vcf -o recal_data.table
#second pass to analyze covariation remaining after recalibration
java -jar GenomeAnalysisTK.jar -T BaseRecalibrator -R human_reference.fasta -I indelrealigner.bam -L 20 -knownSites dbsnp.vcf -knownSites gold_indels.vcf -o recal_data.table
#apply recalibration to sequence data
java -jar GenomeAnalysisTK.jar -T PrintReads -R human_reference.fasta -I indelrealigner.bam -L 20 -BQSR recal_data.table -o recal_reads.bam 

echo "*******call variants" 
#call variants in sequence data
java -jar GenomeAnalysisTK.jar -T HaplotypeCaller -R human_reference.fasta -I recal_reads.bam -L 20 --genotyping_mode DISCOVERY -stand_emit_conf 10 -stand_call_conf 30 -o raw_variants.vcf
